public class TestClass {



	public void test() {

//		String jobId = '08e36000004W51kAAC';
//		CronTrigger ct = [SELECT TimesTriggered, NextFireTime FROM CronTrigger WHERE Id = :jobID];
//		String oldState = ct.State;
//		ct.State = 'COMPLETE';

		//CronJobDetail ctd = [SELECT Id, Name, JobType FROM CronJobDetail WHERE Id = :job.CronJobDetail.Id];

//		Map<Id, CronTrigger> cronTriggerMap = new Map<Id, CronTrigger>( [SELECT Id, State, CronExpression, CronJobDetail.Name FROM CronTrigger] );
//		List<Batch_Job__c> batchJobs = [SELECT Id, Name, Cron_Expression__c, Apex_Class__c, Active__c, State__c, Scheduled_Job_Id__c, Comments__c, Error_Message__c FROM Batch_Job__c ];
//
//		for( Batch_Job__c job :  batchJobs ) {
//			CronTrigger ct = cronTriggerMap.get( job.Scheduled_Job_Id__c );
//			System.debug( '\n\n>>>>>>>>>>BatchJob: ' + job + '\n>>>>>>>>>>CronTriger: ' + ct );
//		}


		//System.debug('This is a test!');
	}

}